title: "Max Warnock's Earth Data Science Portfolio"
theme: jekyll-theme-minimal
logo: /img/max-warnock.png
description: description: |
  <a href="mailto:mawa9468@colorado.edu">mawa9468@colorado.edu</a><br>
  <a href="https://www.linkedin.com/in/maxwell-warnock/">LinkedIn</a>
