title: "Max Warnock"
theme: jekyll-theme-minimal
logo: /img/max-warnock.png
description: |
  <a href="mailto:mawa9468@colorado.edu">mawa9468@colorado.edu</a><br>
  <a href="https://github.com/maxwarnock/">Github</a>
  <a href="https://www.linkedin.com/in/maxwell-warnock/">LinkedIn</a>
  
